name: Build Release

on:
  push:
    tags:
      - "v*.*.*"


env:
  UBUNTU_RTIFACT_NAME: tnn-miner-linux-x86_64.tar.gz
  MACOS_RTIFACT_NAME: tnn-miner-m1-arm64.tar.gz
  WINDOWS_RTIFACT_NAME: tnn-miner-win-x86_64.zip

jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: 'Update system'
      run: |
        # sudo apt-get update
        # sudo apt-get install -y sudo
        scripts/prereqs.sh && scripts/build.sh
        mv ./build/Tnn-miner tnn-miner-linux-amd64
        tar zcvf ${{ env.UBUNTU_RTIFACT_NAME }} tnn-miner-linux-amd64         

    - name: 'Release (linux-amd64)'
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        files: |
          ${{ env.UBUNTU_RTIFACT_NAME }}

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pack
      run: |
        # brew install clang
        brew install fmt
        brew install cmake
        mkdir ./build
        cd ./build
        ln -s /opt/homebrew/Cellar/fmt/10.2.1_1/include/fmt /Users/runner/work/tnn-miner/tnn-miner/src/miner/fmt
        cmake -DTNN_VERSION=$PACKAGE_VERSION ..
        make -j$(nproc)
        cd ../
        mv ./build/Tnn-miner ./tnn-miner-m1-arm64
        tar -zcf ${{ env.MACOS_RTIFACT_NAME }} ./tnn-miner-m1-arm64      

    - name: 'Release (Mac-M1)'
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        files: |
          ${{ env.MACOS_RTIFACT_NAME }}

  Windows:
    # runs-on: windows-latest
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Pack
      run: |
        .\scripts\prereqs.bat ci
        .\scripts\build.bat ci      
          
    - name: 'Release (Win-64)'
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        files: |
          # .\Tnn-miner-win-x64.exe
          ${{ env.WINDOWS_RTIFACT_NAME }}
